### PR TITLE
Update check on staging before going live

### PR DESCRIPTION
**Pull request by alejandroatacho**
### Summary of Changes

1. **Mobile Responsiveness**: Ensured that the `.profile-sidebar` has a 100% width on smaller iOS and Android resolutions to improve mobile responsiveness.
2. **Border Radius**: Added a border radius to `.profile-sidebar` so that it matches the initial left border of the `.profile-content` section for a consistent appearance.
3. **Badge Animation**: Implemented an animation for the "Laboratory" badge to test its functionality on Kawata instead of Codepen.io.
4. **updated .gitignore**: SASS >w> and stuff.

These changes on kawata aim to enhance the overall user experience by improving mobile responsiveness, maintaining visual consistency, and adding interactive elements. 

Please double check kawata-badges.css because, My VSC reformat it but it shouldn't be a problem -w- only in xml jajaja

### CODE REVIEW

**Comment by alejandroatacho** [comment]
clan title in score section and test badge design

**Comment by alejandroatacho** [comment]
Mobile Responsiveness: has been altered a bit for a better design on user profile if they have a screen equal or below to 600 width , to prevent a buggy design that is currently being used.

**Comment by alejandroatacho** [comment]
added id to the clan html so I can target it easier without targetting other pages class name:

added mobile responsiveness to clan for smaller screen and used rem padding for the text so it has some space next to clan logo.

**Comment by alejandroatacho** [comment]
# Update: Custom Path and Base Loading

In this update, I have made several changes to improve the organization of the project and ensure easy management of custom features.

## Custom Path

I have created a custom path for all project-specific additions. This allows for better organization and separation from the original codebase. The custom path includes all new features and modifications to the project. 

If, in the future, you decide to revert to the original setup, you can simply delete the custom path/folder, and the project will return to its original state.

## Base Loading

The base loading has been updated to use the custom path, ensuring that all new features and modifications are loaded correctly.

## Git Ignore Updates

The `.gitignore` file has been updated to exclude `.scss` files and a `/test` folder. This ensures that these files are not uploaded to the repository, keeping the project clean and well-organized.

**Comment by alejandroatacho** [comment]
Last Pull Request Update till something gets implemented, to continue from a new PR.

**Comment by g1-1-1** [comment]
LGTM looks good 👍

**Comment by iotazz** [comment]
looks good to me!

**Comment by 7ez** [comment]
2 spaces users smh

**Comment by iotazz** [comment]
> 2 spaces users smh

zzz

**Comment by alejandroatacho** [comment]
## Changes Applied

The following changes were applied to the code:

### CSS

- Added styles to target the gray circle icons and "Offline" text on the first line and the rest on the second line using `display:flex` for a maximum width of 600px.

- Added styles to move the image to the middle of the profile name section on the profile sidebar.

- Fix Design
- 
### SASS

- Added styles to target and apply margin properties to all `h1` elements in `.magic.table.floating.right` class.

- Added styles to make the `img` and `a` elements of `.profile-name` class appear next to each other using `display:flex`.

- Added styles to make the `div` and `a` elements of `.user.dev` class appear next to each other using `display:flex`.

- Removed the @import "expirement";, so the leaderboard td plan doesn't get uploaded

**Comment by 7ez** [comment]
> ## Changes Applied
> 
> The following changes were applied to the code:
> 
> ### CSS
> 
> - Added styles to target the gray circle icons and "Offline" text on the first line and the rest on the second line using `display:flex` for a maximum width of 600px.
> 
> - Added styles to move the image to the middle of the profile name section on the profile sidebar.
> 
> - Fix Design
> - 
> ### SASS
> 
> - Added styles to target and apply margin properties to all `h1` elements in `.magic.table.floating.right` class.
> 
> - Added styles to make the `img` and `a` elements of `.profile-name` class appear next to each other using `display:flex`.
> 
> - Added styles to make the `div` and `a` elements of `.user.dev` class appear next to each other using `display:flex`.
> 
> - Removed the @import "expirement";, so the leaderboard td plan doesn't get uploaded

Nice gpt-4 usage

**Comment by alejandroatacho** [comment]
> > ## Changes Applied
> > The following changes were applied to the code:
> > ### CSS
> > 
> > * Added styles to target the gray circle icons and "Offline" text on the first line and the rest on the second line using `display:flex` for a maximum width of 600px.
> > * Added styles to move the image to the middle of the profile name section on the profile sidebar.
> > * Fix Design
> > 
> > 
> > ### SASS
> > 
> > * Added styles to target and apply margin properties to all `h1` elements in `.magic.table.floating.right` class.
> > * Added styles to make the `img` and `a` elements of `.profile-name` class appear next to each other using `display:flex`.
> > * Added styles to make the `div` and `a` elements of `.user.dev` class appear next to each other using `display:flex`.
> > * Removed the @import "expirement";, so the leaderboard td plan doesn't get uploaded
> 
> Nice gpt-4 usage

sorry, but we have to do this in work field or else we get in trouble with upper management this is just how we report and has become a custom. 

It's a template .readme Ive made in my repository to use for work.

**Pull request closed without merging**
